spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/boardservice
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

file:
  dir: '파일 업로드할 디렉토리 절대경로'
  requestUrl: "http://localhost:8080/upload-file/"
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace